### ISSUE TITLE
The size of hard disk space

### ISSUE THREAD

**Issue by DaiChibret** [CESSProject/cess#12]
I have a question when I want put my database to the hard disk space, I have no idea what is the size of the hard disk space is appropriate for my database?

**Comment by heyworld88** [comment]
Hi, thanks for your question. Actually there is no special requirement for the space of the mining machine, and ordinary hard disks can be used for mining. I wish this anwser could fix your confusion.

**Comment by Cess-OpenSource** [comment]
normally 200G - 2T is appropriate size for most cases
