### ISSUE TITLE
CESS pallet-sminer

### ISSUE THREAD

**Issue by Aranck** [CESSProject/cess#14]
Hi there, I am a cess fan and watched the last week's CESS technology presentation. The speaker has shared a lot of information about CESS how to develop on the substrate at that moment. The best point that makes me interesting is CESS created a pallet of sminer in the substrate.

**Comment by heyworld88** [comment]
Hello, thanks for your advice.  I feel so honored. yes, we keep developing on substrate pallet of sminer. our organization designed that using on_nonzero_unbalanced technology to achieve the OnUnbalanced trait function of receiving a new token in the account that registered in the pallet.
