### ISSUE TITLE
Add back rust-toolchain.toml so all dev have a consistent compiling env

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/cess#190]
Refer to Substrate example: 
https://github.com/substrate-developer-hub/substrate-node-template/blob/main/rust-toolchain.toml

But using this rust-toolchain file causes you to download a new nightly version and recompile your code everyday. So you can fix the compiler nightly version. [Example here](https://github.com/hkwtf/cess/blob/0.6.1-space-prove/rust-toolchain.toml).

**Comment by ytqaljn** [comment]
Thank you for your suggestion. We have made the corresponding changes.
