### ISSUE TITLE
Only 2 Miners assigned for Large Files.

### ISSUE THREAD

**Issue by tehsunnliu** [CESSProject/cess#200]
Hi, recently I've noticed that when I upload small files all the time 3 miners are assigned to store the file segments. However, in case of larger files like 1GiB, only 2 miners are assigned. Why is this so? 

Below is the FID of the file with 2 assigned miners. 
FID: 2b15b2919269b6ee2685e492a907f6aea76fddd232966c577dac6bc959d72d8c

**Comment by ytqaljn** [comment]
Because there is an upper limit to the number of random selections, within this limit, as many as possible, three miners who meet the conditions will be randomly selected. When uploading large files, the number of miners who meet the conditions decreases, which reduces the probability of selecting three miners who meet the conditions within the number of times.
code:
https://github.com/CESSProject/cess/blob/0.6.1-space-prove/c-pallets/file-bank/src/functions.rs#L291

**Comment by tehsunnliu** [comment]
I see, so the primary criterion is they should have enough available space. But keeping an upper limit makes larger files to get uploaded forever and suppose there is not even 1 miner that can store a big chunk of data, that file will never get uploaded to the miners. In fact, in my opinion, there should not be any upper limit on the number of miners assigned and the file should be segmented so that its able to be stored on at least some number of miners. Right now I'm not sure why is this upper limit set, If you could explain this a little, it will be helpful in understanding. Thanks.

**Comment by ytqaljn** [comment]
Because these tasks need to be completed in one block within 6 seconds. So there's no way to keep selecting.

**Comment by tehsunnliu** [comment]
I still didn't get a clear picture. Why the task has to be completed in one block? By the way if the miners fail to store the files, new miners are selected. So I wonder how come there is no way to keep selecting?

**Comment by ytqaljn** [comment]
Rules for blockchain transactions in the substrate framework

**Comment by tehsunnliu** [comment]
Well, unfortunately this doesn't answer my doubt clearly.
Currently, when a user uploads file it takes hours and hours to distribute it to the miners. And during this time a number of times miners are reassigned due to failed attempts to deliver the segment to the miner. Then how come these tasks has to be completed in one block? Only selecting number of minsers can be done within a block.

**Comment by ytqaljn** [comment]
Go and learn about the blockchain foundation built by the substrate framework.

**Comment by tehsunnliu** [comment]
Wao this is your answer. That's of great help.

**Comment by tehsunnliu** [comment]
And this is very rude of you and unprofessional.

**Comment by ytqaljn** [comment]
Sorry, my English is not good, so when I finally saw your answer, I thought it solved your confusion

**Comment by ytqaljn** [comment]
I have already told you that this must be done within a block, and you have to delve into it yourself, still unable to understand. I really don't know what else to tell you. A transaction must be executed within a block, which is the rule.

**Comment by ytqaljn** [comment]
https://docs.substrate.io/learn/transaction-lifecycle/
![image](https://github.com/CESSProject/cess/assets/59600396/7eefed1b-1cc3-46ea-a2c7-daf850051b4d)
https://docs.substrate.io/learn/transaction-types/
![image](https://github.com/CESSProject/cess/assets/59600396/4782bdb8-dd4a-400c-ad3d-4d44bf3b0baf)

**Comment by tehsunnliu** [comment]
My point is why only up to 3 miners are selected, why can't we select number of minsers dynamically based on the file size. If a bigger file is uploaded it should be distributed to even more miners so that it miners will less storage space can also store it's segments and easier to find miners who meet the criteria and larger files won't take forever to upload.

**Comment by ytqaljn** [comment]
Because the allocation quantity is determined based on the current fragment size and segment size. The current segment size is 16Mib and will be divided into three fragments. It is not related to the size of the file itself, we consider it based on recoverability, with three being the optimal number

**Comment by tehsunnliu** [comment]
So any solution for larger files that takes very long to get distributed to the miners?

**Comment by ytqaljn** [comment]
The current reassignment process has some bugs that will be fixed in 0.7.0 and will be resolved by improving the accuracy of random selection, rather than increasing the number of random selections.

**Comment by tehsunnliu** [comment]
Okay waiting for 0.7.0 then.
