### ISSUE TITLE
Issues about data chunk during challenge process

### ISSUE THREAD

**Issue by hongxiangz** [CESSProject/cess#203]
When I study the challenge process of cess, I noticed that when challenging data, data blocks are formed by dividing the fragments into smaller chunks. Why data is chllenged in forms of chunk rather than data fragments, what's the point of this design?

**Comment by onionhon** [comment]
I guess it's one of the defalut famework setting. Please refer to
[](
https://app.gitbook.com/o/kiTNX10jBU59sjnYZbiH/s/Ipo9x78xtry0XljLDdDf/learn/technical-highlights/trusted-continuity-proof)
