### ISSUE TITLE
Ink! contracts called from testnet.cess.cloud fail

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/cess#213]
## Problem

After deploy a flipper ink! contract in my CESS v0.6.0 local dev node. When calling a read op from [testnet.cess.cloud](https://testnet.cess.cloud):

![Screenshot 2023-08-23 at 12 46 30](https://github.com/CESSProject/cess/assets/898091/224b990f-d6da-460a-a9d5-0503a8b3f28f)

A write op will be as follow:

![Screenshot 2023-08-23 at 12 48 13](https://github.com/CESSProject/cess/assets/898091/c095f004-2e89-4481-8a6a-783dd4cd7e05)

Calling the same contract in https://cloudflare-ipfs.com/ipns/dotapps.io. Read op:

![Screenshot 2023-08-23 at 12 41 32](https://github.com/CESSProject/cess/assets/898091/eb11cae3-a753-44f0-97f1-b5cc5ad07ed9)

A write op:

![Screenshot 2023-08-23 at 12 41 51](https://github.com/CESSProject/cess/assets/898091/310e99ad-8798-4697-9039-3bf94bea8b5a)

## Possible Solution

Upgrade the Polkadot.js Apps hosted at https://testnet.cess.cloud/

**Comment by ytqaljn** [comment]
It seems that our Polkadot.js version is outdated. Thank you for your suggestion, and we will upgrade it in the future.
