### ISSUE TITLE
issues about random challenge

### ISSUE THREAD

**Issue by onionhon** [CESSProject/cess#221]
It happens that, the verification life cycle of random challenges are smaller than the computational proof cycle.

**Comment by ytqaljn** [comment]
fix bug:

https://github.com/CESSProject/cess/pull/215/commits/1b5cb529f3d9baf2ae0f9e3d5458ac2dc21f8a98#diff-ca854b8464a0f070ed5b6e8759e5a9ef2962ce8af40d1777446f645d6580ac05R425-R429
