### ISSUE TITLE
issues about randome challenge 2

### ISSUE THREAD

**Issue by onionhon** [CESSProject/cess#222]
The verification results of random challenges will not be cleared,  in special circumstances, causing an impact.

**Comment by ytqaljn** [comment]
fix bug:

https://github.com/CESSProject/cess/pull/215/commits/b5e77cdeeae041a3c6a35d88fb3465bc850ee08a#diff-ca854b8464a0f070ed5b6e8759e5a9ef2962ce8af40d1777446f645d6580ac05R1004-R1007
