### ISSUE TITLE
the reputation score didn't not positioned well. 

### ISSUE THREAD

**Issue by onionhon** [CESSProject/cess#223]
**Possible solution**: Adding reputation score for consensus after completing the verification task.
**Action**: On-going

**Comment by ytqaljn** [comment]
https://github.com/CESSProject/cess/pull/215/commits/f64be701ae34acb6ebc23366b7ebc72d2e5514a5#diff-ca854b8464a0f070ed5b6e8759e5a9ef2962ce8af40d1777446f645d6580ac05R639-R728
