### ISSUE TITLE
issues about storage miner's debt

### ISSUE THREAD

**Issue by onionhon** [CESSProject/cess#224]
**Possible Solution**: When miners are in a debt situation, the additional pledge from the debt portion will be added to the bonus poo
**Status**: on-going

**Comment by ytqaljn** [comment]
https://github.com/CESSProject/cess/pull/215/commits/3bb6ca807e49bd31dd3ffa5b626d4e2d1af417ab#diff-30c617cf01d014c0e882cf4c64b66e5f459de77270aa8617a71c6fc93a9a143aR410-R419
