### ISSUE TITLE
Unify the unit of currency/balance between Substrate pallet-balance and pallet-evm

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/cess#234]
Currently, **1M of native CESS tokens** (on Substrate side) = **1 EVM CESS tokens**

**Comment by ytqaljn** [comment]
Thank you for your discovery. We will fix it in the next version.

**Comment by jimmychu0807** [comment]
@ytqaljn we will need to open this issue and discuss: 1) whether to fix it, 2) the approach to fix it.

The reason that currently 1M of native CESS tokens is shown as 1 EVM CESS tokens is because all EVM wallets use 18 decimals to read the EVM chain native token. There is no way we can configure the decimal places as in reading ERC-20 contracts. 

The current approach to fix it are:

1. Change the token decimal places in Substrate native side to 18. This is the approach [Moonbeam takes](https://github.com/moonbeam-foundation/moonbeam/blob/master/runtime/moonbeam/src/lib.rs#L133). The implication is that this affect the Substrate native tokens.

2. Adding a currency adaptor, as Darwinia does, [example here](https://github.com/darwinia-network/darwinia-common/blob/6a9392cfb9fe2c99b1c2b47d0c36125d61991bb7/frame/dvm/ethereum/src/adapter.rs#L136-L150). Darwinia Substrate native token is 10^9 (9 decimal places) and need to multiply/divide by another 10^9 to convert to EVM token unit. There are also some [runtime config hooking work](https://github.com/darwinia-network/darwinia-common/blob/6a9392cfb9fe2c99b1c2b47d0c36125d61991bb7/node/runtime/pangolin/src/pallets/evm.rs#L183-L187) to extend the pallet to use a currency adapter.

Ref:
- [Substrate SE discussion](https://substrate.stackexchange.com/a/6694/121)

**Comment by ytqaljn** [comment]
Thank you for your suggestion. Although the second option is more cumbersome, it will have less impact on our network. If you change the decimal place of cess, it will have an impact on other programs such as bucket and go-sdk.

**Comment by jimmychu0807** [comment]
回到 [SE 讨论](https://substrate.stackexchange.com/questions/6692/how-to-change-evm-token-decimals/6694#6694). 

我想 Darwinia 不再维护 CurrencyAdapter 应该是觉得是维护起来很麻烦。除了每次乘/除以外，我想到就是手续费。那 evm 上的手续费就是奇高。就算本身很少，但要乘个 10^9 (它们，我们是 10^6). 还有，到 DEX/CEX 交易所时，你怎样兑？是用 evm token 的单位还是 substrate token 单位? 想到这些，我都觉得直接改到 10^18 就痛一次较好。
