### ISSUE TITLE
bucket error log: [cess.New] json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes

### ISSUE THREAD

**Issue by cnhotfire** [CESSProject/cess#235]
my cess bucket report and restarting: 
++ 2023-10-07 04:23:11 Rpc addresses: [ws://127.0.0.1:9944 wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/]
++ 2023-10-07 04:23:11 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
XX 2023-10-07 04:23:11 [cess.New] json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes

I tried the following but still no solution：
cess stop
cess down
cess purge
cess profile testnet
cess config set
############################
cess status
NAMES        STATUS
chain        Up 47 minutes
watchtower   Up 52 minutes (healthy)
bucket       Restarting (1) 38 seconds ago
############################
cess bucket stat
XX 2023-10-07 04:32:30 json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes
############################
cess config show
{
  "node": {
    "mode": "storage",
    "externalIp": "",
    "domainName": "",
    "chainWsUrl": "ws://127.0.0.1:9944",
    "profile": "testnet",
    "backupChainWsUrls": [
      "wss://testnet-rpc0.cess.cloud/ws/",
      "wss://testnet-rpc1.cess.cloud/ws/"
    ]
  },
  "chain": {
    "name": "cess",
    "port": 30336
  },
  "bucket": {
    "port": 15001,
    "space": 2000,
    "incomeAccount": "cXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "signPhrase": "XXXX foam edit XXXXX stumble XXXXX void XXXXX orphan XXXXX embrace XXXX",
    "diskPath": "/data4/cess",
    "bootAddr": "_dnsaddr.boot-kldr-testnet.cess.cloud"
  }
}
############################
I have disabled ipv6，network is ok
$ ping testnet-rpc0.cess.cloud
PING testnet-rpc0.cess.cloud (104.21.59.6) 56(84) bytes of data.
64 bytes from 104.21.59.6 (104.21.59.6): icmp_seq=1 ttl=60 time=0.767 ms
64 bytes from 104.21.59.6 (104.21.59.6): icmp_seq=2 ttl=60 time=0.684 ms
^C
--- testnet-rpc0.cess.cloud ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 0.684/0.725/0.767/0.041 ms
$ ping testnet-rpc1.cess.cloud
PING testnet-rpc1.cess.cloud (172.67.167.97) 56(84) bytes of data.
64 bytes from 172.67.167.97 (172.67.167.97): icmp_seq=1 ttl=60 time=0.708 ms
64 bytes from 172.67.167.97 (172.67.167.97): icmp_seq=2 ttl=60 time=0.718 ms
############################
system info: 
Ubuntu 22.04.3 LTS
5.15.0-86-generic

docker info:
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

cess info:
Node mode: storage
Profile: testnet
nodeadm version: v0.4.4
Docker images:
  config-gen: config-gen 1.4.6 20227e510d85
  chain: cess-node 0.7.0-unknown d7bc4ab3739a
  bucket: bucket v0.7.1 c2160c94f3b7

**Comment by cnhotfire** [comment]
After 5 hours, the docker logs bucket output:
++ 2023-10-07 09:27:12 Rpc addresses: [ws://127.0.0.1:9944 wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud /ws/]
++ 2023-10-07 09:27:12 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
OK 2023-10-07 09:27:16 Connection to boot node successful: 12D3KooWLtpEaPbJhTyC8qoRp8PrjHy4ou7TCSY3XEtzNsh4Jatb
OK 2023-10-07 09:27:16 Connection to boot node successful: 12D3KooWHY6BRu2MtG9SempACgYCcGHRSEai2ZkWY3E4VKDYrqh9
OK 2023-10-07 09:27:17 Connection to boot node successful: 12D3KooWAdyc4qPWFHsxMtXvSrm7CXNFhUmKPQdoXuKQXki69qBo
++ 2023-10-07 09:27:17 Local peer id: 12D3KooWAxWJHzuHaP3eb9D2FP8PQ7MNtLEyhgve5f3S5jwdafsL
++ 2023-10-07 09:27:17 Chain network: cess-testnet
++ 2023-10-07 09:27:17 P2P network: cess-testnet
OK 2023-10-07 09:27:18 Synchronization main chain completed: 377252
++ 2023-10-07 09:27:29 Successfully found 12D3KooWAdyc4qPWFHsxMtXvSrm7CXNFhUmKPQdoXuKQXki69qBo for registration
++ 2023-10-07 09:27:30 Workspace: /opt/bucket-disk/cXh2P8NFaZcN3fMo6u81YzM51EANATyrnxmj549jrdwFn2HaU/bucket
OK 2023-10-07 09:27:31 Start successfully
#########################################
However, $ cess bucket stat          still outputs:
XX 2023-10-07 14:50:35 json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes

**Comment by cnhotfire** [comment]
I discovered another strange thing. 
cess config show shows "diskPath": "/data4/cess". 
But the log output workspace of the bucket is /opt/bucket-disk/cXh2P8NFaZcN3fMo6u81YzM51EANATyrnxmj549jrdwFn2HaU/bucket. 
Is the diskPath in the config not taking effect?

**Comment by cnhotfire** [comment]
$ ls /opt/bucket-disk/cXh2P8NFaZcN3fMo6u81YzM51EANATyrnxmj549jrdwFn2HaU/bucket
ls: cannot access '/opt/bucket-disk/cXh2P8NFaZcN3fMo6u81YzM51EANATyrnxmj549jrdwFn2HaU/bucket': No such file or directory
$ ls /data4/cess/cXh2P8NFaZcN3fMo6u81YzM51EANATyrnxmj549jrdwFn2HaU/bucket/
acc  db  file  log  peers  pois  random  space  stag  tmp

I think It's a log report issue

**Comment by ytqaljn** [comment]
cc @AstaFrode

**Comment by AstaFrode** [comment]
@cnhotfire Take a look at your chain logs: `docker logs chain`.
`/opt/bucket-disk` is the path within the docker container, corresponding to the external `/data4/cess`, just focus on the external path.

**Comment by cnhotfire** [comment]
when I restat cess, the bucker error log is reported again:
 ++ 2023-10-11 17:32:37 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
XX 2023-10-11 17:32:38 [cess.New] json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes

docker logs -f -n 100 chain:
2023-10-11 17:33:13 💤 Idle (150 peers), best: #439712 (0xbf7f…51fc), finalized #439710 (0x116e…9151), ⬇ 80.9kiB/s ⬆ 50.8kiB/s    
2023-10-11 17:33:18 💤 Idle (150 peers), best: #439712 (0xbf7f…51fc), finalized #439710 (0x116e…9151), ⬇ 77.5kiB/s ⬆ 56.0kiB/s    
2023-10-11 17:33:18 ✨ Imported #439713 (0xf6d9…60e0)    
2023-10-11 17:33:23 💤 Idle (150 peers), best: #439713 (0xf6d9…60e0), finalized #439711 (0x9602…7ed2), ⬇ 69.3kiB/s ⬆ 55.9kiB/s    
2023-10-11 17:33:24 ✨ Imported #439714 (0xaac3…ea87)    
2023-10-11 17:33:28 💤 Idle (150 peers), best: #439714 (0xaac3…ea87), finalized #439712 (0xbf7f…51fc), ⬇ 80.2kiB/s ⬆ 55.3kiB/s    
2023-10-11 17:33:30 ✨ Imported #439715 (0xa052…1d75)    
2023-10-11 17:33:33 💤 Idle (150 peers), best: #439715 (0xa052…1d75), finalized #439713 (0xf6d9…60e0), ⬇ 79.9kiB/s ⬆ 48.4kiB/s    
2023-10-11 17:33:36 ✨ Imported #439716 (0x07e2…7359)    
2023-10-11 17:33:38 💤 Idle (150 peers), best: #439716 (0x07e2…7359), finalized #439714 (0xaac3…ea87), ⬇ 67.1kiB/s ⬆ 45.7kiB/s    
2023-10-11 17:33:42 ✨ Imported #439717 (0x4075…16eb)    
2023-10-11 17:33:43 💤 Idle (150 peers), best: #439717 (0x4075…16eb), finalized #439714 (0xaac3…ea87), ⬇ 84.2kiB/s ⬆ 48.6kiB/s    
2023-10-11 17:33:48 💤 Idle (150 peers), best: #439717 (0x4075…16eb), finalized #439715 (0xa052…1d75), ⬇ 73.2kiB/s ⬆ 50.0kiB/s    
2023-10-11 17:33:48 ✨ Imported #439718 (0xfef4…eedb)    
2023-10-11 17:33:53 💤 Idle (150 peers), best: #439718 (0xfef4…eedb), finalized #439716 (0x07e2…7359), ⬇ 80.4kiB/s ⬆ 73.8kiB/s    
2023-10-11 17:33:54 ✨ Imported #439719 (0x008f…b6fa)    
2023-10-11 17:33:58 💤 Idle (150 peers), best: #439719 (0x008f…b6fa), finalized #439717 (0x4075…16eb), ⬇ 92.0kiB/s ⬆ 77.4kiB/s    
2023-10-11 17:34:00 ✨ Imported #439720 (0xdfaf…91e1)    
2023-10-11 17:34:03 💤 Idle (150 peers), best: #439720 (0xdfaf…91e1), finalized #439718 (0xfef4…eedb), ⬇ 67.7kiB/s ⬆ 77.1kiB/s    
2023-10-11 17:34:06 ✨ Imported #439721 (0x9e01…1985)

**Comment by AstaFrode** [comment]
@cnhotfire The reason for this error is that the structure read back from the chain does not match the structure defined by the storage node. Please check whether your chain node is normal and whether the chain before v0.7 has been stopped.

**Comment by cnhotfire** [comment]
How do I check whether the chain node is normal? This is my first time deploying cess @AstaFrode

**Comment by AstaFrode** [comment]
@cnhotfire Execute `cess status` and `cess version`

**Comment by cnhotfire** [comment]
@AstaFrode 
$ cess status
NAMES        STATUS
chain        Up 13 hours
bucket       Restarting (1) 46 seconds ago
watchtower   Up 13 hours (healthy)

$ cess version
Node mode: storage
Profile: testnet
nodeadm version: v0.4.4
Docker images:
  config-gen: config-gen 1.4.6 20227e510d85
  chain: cess-node 0.7.0-unknown d7bc4ab3739a
  bucket: bucket v0.7.1 c2160c94f3b7

**Comment by AstaFrode** [comment]
@cnhotfire Try again after updating the image.
`cess pullimg`
`cess restart bucket`

**Comment by cnhotfire** [comment]
@AstaFrode Still can't solve it
$ cess pullimg
testnet: Pulling from cesslab/config-gen
Digest: sha256:d1e6f7e28725a733d37550ed051ac7c0f28f73cd9616e1e332e3b472d8d48613
Status: Image is up to date for cesslab/config-gen:testnet
docker.io/cesslab/config-gen:testnet
[+] Pulling 6/6
 ✔ chain Pulled                                                                                                                                                                                                       1.1s 
 ✔ bucket 3 layers [⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                       2.6s 
   ✔ 96526aa774ef Pull complete                                                                                                                                                                                       0.6s 
   ✔ 9deb4066b58f Pull complete                                                                                                                                                                                       0.5s 
   ✔ 18ad35595168 Pull complete                                                                                                                                                                                       0.8s 
 ✔ watchtower Pulled            

$ cess restart bucket
[+] Stopping 1/0
 ✔ Container bucket  Stopped                                                                                                                                                                                          0.0s 
Going to remove bucket
[+] Removing 1/0
 ✔ Container bucket  Removed                                                                                                                                                                                          0.0s 
[+] Running 3/3
 ✔ Container bucket      Started                                                                                                                                                                                      0.0s 
 ✔ Container chain       Running                                                                                                                                                                                      0.0s 
 ✔ Container watchtower  Running            

$ docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED          STATUS                         PORTS     NAMES
ff6033046c95   cesslab/cess-bucket:testnet   "cess-bucket run -c …"   38 seconds ago   Restarting (1) 9 seconds ago             bucket
62b544b2bcb2   cesslab/cess-chain:testnet    "./cess-node --base-…"   13 hours ago     Up 13 hours                              chain
5f7a52b74e1d   containrrr/watchtower         "/watchtower --clean…"   13 hours ago     Up 13 hours (healthy)                    watchtower

$ docker logs -f -n 10 bucket
XX 2023-10-12 06:39:57 [cess.New] json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes
++ 2023-10-12 06:40:48 Rpc addresses: [ws://127.0.0.1:9944 wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/]
++ 2023-10-12 06:40:48 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
XX 2023-10-12 06:40:48 [cess.New] json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes
++ 2023-10-12 06:41:48 Rpc addresses: [ws://127.0.0.1:9944 wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/]
++ 2023-10-12 06:41:48 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
XX 2023-10-12 06:41:49 [cess.New] json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes
++ 2023-10-12 06:42:49 Rpc addresses: [ws://127.0.0.1:9944 wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/]
++ 2023-10-12 06:42:49 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
XX 2023-10-12 06:42:49 [cess.New] json: cannot unmarshal number into Go struct field SysProperties.Ss58Format of type types.Bytes

**Comment by AstaFrode** [comment]
@cnhotfire You can feedback your server information to our official staff in [discord](https://discord.com/invite/mYHTMfBwNS), or send it directly to frode@cess.one and we will help you solve it.

**Comment by AstaFrode** [comment]
@cnhotfire Use `netstat -nlpt` to check the started service and check whether the service name corresponding to port 9944 is cess-node. If not, you can use the `kill <pid>` command to kill it and then restart: `cess restart`.

**Comment by cnhotfire** [comment]
@AstaFrode 
$  netstat -antup | grep 9944
tcp        0      0 127.0.0.1:9944          0.0.0.0:*               LISTEN      2877729/./cess-node 
It's cess-node

**Comment by cnhotfire** [comment]
@AstaFrode thx，It conflicts with subspace node, which is also part of the Polkadot ecosystem.
