### ISSUE TITLE
"✘ Network kaleido  Error" While starting Consens Miner.

### ISSUE THREAD

**Issue by tehsunnliu** [CESSProject/cess#251]
Hi, while trying to start the consensus miner I'm getting the below error
```bash
:~$ sudo cess start
[+] Running 1/0
 ✘ Network kaleido  Error                                                                                                                0.0s 
failed to create network kaleido: Error response from daemon: Pool overlaps with other one on this address space
```

This is CESS version I'm using

```bash
:~$ docker network ls
Node mode: authority
Profile: testnet
nodeadm version: v0.4.4
Docker images:
  config-gen: config-gen 1.4.6 20227e510d85
  chain: cess-node 0.7.4-unknown 85c1d88b3bf8
  kld-agent: kaleido-rotator 0.2.6-testnet af22e54a4e68
  kld-sgx: kaleido 0.2.5-testnet c9f0ee9f5934
```

And the docker networks
```bash
:~$ sudo docker network ls
NETWORK ID     NAME                 DRIVER    SCOPE
522fcb73380e   bridge               bridge    local
0777207ffbef   host                 host      local
07a35af1dd56   none                 null      local
```

My config file 
```bash
{
  "node": {
    "mode": "authority",
    "externalIp": "45.77.47.184",
    "domainName": "",
    "chainWsUrl": "ws://127.0.0.1:9944",
    "profile": "testnet",
    "backupChainWsUrls": [
      "wss://testnet-rpc0.cess.cloud/ws/",
      "wss://testnet-rpc1.cess.cloud/ws/"
    ],
    "kldSgxImageId": ""
  },
  "chain": {
    "name": "Ginger-718599",
    "port": 30336
  },
  "kaleido": {
    "agentPort": 10010,
    "kaleidoPort": 4001,
    "bootPeerIds": "12D3KooWAdyc4qPWFHsxMtXvSrm7CXNFhUmKPQdoXuKQXki69qBo,12D3KooWLtpEaPbJhTyC8qoRp8PrjHy4ou7TCSY3XEtzNsh4Jatb,12D3KooWHY6BRu2MtG9SempACgYCcGHRSEai2ZkWY3E4VKDYrqh9",
    "stashAccount": "cXkMzNVe1TC8ju1bUuxazHPM2jyuz8Ei2xQdXk5zWWANV7mz5",
    "controllerPhrase": "december ... marine",
    "allowLogCollection": true,
    "bootDnsaddr": "/dnsaddr/boot-kldr-testnet.cess.cloud"
  }
}

```

**Comment by tehsunnliu** [comment]
Is this error cause because there is a phala container running on the same system?
<img width="1010" alt="image" src="https://github.com/CESSProject/cess/assets/15224865/f61bb456-066d-485f-a45c-5fd85dc7fd0e">

**Comment by democ98** [comment]
When starting the consensus container, a kaleido network will be created. The network will be assigned a fixed IP segment, and its gateway is 172.18.0.1. If other networks on your machine occupy this IP segment, the creation will fail.
Please check: docker network inspect <Your NETWORK ID>

**Comment by tehsunnliu** [comment]
Okay I just checked all the networks with `docket network inspect` and indeed one of the application is using 172.18.0.1
Is there anyway I can configure Kaleido to use some other gateway address?

**Comment by democ98** [comment]
`vim /opt/cess/nodeadm/build/docker-compose.yaml`
![a71db917-d0a5-42a4-9cb0-5d485110689c](https://github.com/CESSProject/cess/assets/69138672/612b3c77-d551-4c10-9849-126c1c5d39bb)

**Comment by democ98** [comment]
`vim /opt/cess/nodeadm/build/docker-compose.yaml`
This is the docker compose file started by the consensus node. You must modify its content.

![a71db917-d0a5-42a4-9cb0-5d485110689c](https://github.com/CESSProject/cess/assets/69138672/1662efac-a485-47e5-84b0-8036ec1f2333)

Modify the gateway IP (like 172.19.0.0) and then modify the IP used by each container(lie 172.19.0.4)

**Comment by tehsunnliu** [comment]
Perfect! I updated the IP in all the places and it's working now.
Thank you.
