### ISSUE TITLE
cess reconfig issue

### ISSUE THREAD

**Issue by cnhotfire** [CESSProject/cess#252]
I have a server,  because I didn't have enough TCESS to stake 8000G of storage a few days ago, I initially staked 2000G with 8000 TCESS. 
But now I've received enough TCESS, and I want to reconfigure and increase bucket.space to 8000G. 
However, when I try 
`cess stop`
`cess config set`
`cess start`

 I encounter an issue. 
Even though `cess config show` shows that bucket.space has been increased to 8000, but the funds in my wallet haven't changed at all, 'reserved' is still at 8000

**Comment by cnhotfire** [comment]
Now, I try 
`cess purge`
and change a new wallet, 
bucket logs report:
++ 2023-11-02 10:47:07 Rpc addresses: [ws://127.0.0.1:9944 wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/]
++ 2023-11-02 10:47:07 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1082400]

goroutine 1 [running]:
github.com/CESSProject/p2p-go/core.GetExternalIp()
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/core/utils.go:126 +0x360
github.com/CESSProject/p2p-go/core.NewBasicNode({0x1a03750?, 0xc000046030}, 0x3a99, {0xc000980000, 0x49}, {0x0, 0x0}, {0xc0004a6710, 0x1, 0x1}, ...)
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/core/node.go:373 +0x2e5
github.com/CESSProject/p2p-go/config.(*Config).NewNode(0x20?, {0x1a03750?, 0xc000046030?})
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/config/config.go:56 +0x285
github.com/CESSProject/p2p-go.NewWithoutDefaults({0x1a03750, 0xc000046030}, {0xc0005f2080, 0x5, 0x8})
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/p2p.go:54 +0x85
github.com/CESSProject/p2p-go.New(...)
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/p2p.go:40
github.com/CESSProject/cess-bucket/cmd/console.runCmd(0xc000004f00?, {0x159debb?, 0x2?, 0x2?})
        /opt/target/cmd/console/run.go:100 +0xa90
github.com/spf13/cobra.(*Command).execute(0xc000004f00, {0xc000118180, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2424d80)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/CESSProject/cess-bucket/cmd/console.Execute()
        /opt/target/cmd/console/root.go:29 +0x32
main.main()
        /opt/target/cmd/main.go:23 +0x15b

how can I fix the server?

**Comment by cnhotfire** [comment]
Now, I try 
`cess purge`
and change a new wallet, 
bucket logs report:
++ 2023-11-02 10:47:07 Rpc addresses: [ws://127.0.0.1:9944 wss://testnet-rpc0.cess.cloud/ws/ wss://testnet-rpc1.cess.cloud/ws/]
++ 2023-11-02 10:47:07 Bootnodes: [_dnsaddr.boot-kldr-testnet.cess.cloud]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1082400]

goroutine 1 [running]:
github.com/CESSProject/p2p-go/core.GetExternalIp()
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/core/utils.go:126 +0x360
github.com/CESSProject/p2p-go/core.NewBasicNode({0x1a03750?, 0xc000046030}, 0x3a99, {0xc000980000, 0x49}, {0x0, 0x0}, {0xc0004a6710, 0x1, 0x1}, ...)
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/core/node.go:373 +0x2e5
github.com/CESSProject/p2p-go/config.(*Config).NewNode(0x20?, {0x1a03750?, 0xc000046030?})
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/config/config.go:56 +0x285
github.com/CESSProject/p2p-go.NewWithoutDefaults({0x1a03750, 0xc000046030}, {0xc0005f2080, 0x5, 0x8})
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/p2p.go:54 +0x85
github.com/CESSProject/p2p-go.New(...)
        /go/pkg/mod/github.com/!c!e!s!s!project/p2p-go@v0.2.4/p2p.go:40
github.com/CESSProject/cess-bucket/cmd/console.runCmd(0xc000004f00?, {0x159debb?, 0x2?, 0x2?})
        /opt/target/cmd/console/run.go:100 +0xa90
github.com/spf13/cobra.(*Command).execute(0xc000004f00, {0xc000118180, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2424d80)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/CESSProject/cess-bucket/cmd/console.Execute()
        /opt/target/cmd/console/root.go:29 +0x32
main.main()
        /opt/target/cmd/main.go:23 +0x15b

how can I fix the server?

**Comment by ytqaljn** [comment]
@AstaFrode  cc

**Comment by AstaFrode** [comment]
@cnhotfire Fixed in bucket v0.7.5
