### ISSUE TITLE
Multi-sig solution

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/cess#260]
@tehsunnliu @ytqaljn 

Without using any external solutions, the following demonstrate the default multi-sig UX in Polkadot. Is that enough for our use case?

- [Polkadot Multi-sig support](https://wiki.polkadot.network/docs/learn-account-multisig)
- [Video walkthru on Polkadot multi-sig](https://www.youtube.com/watch?v=-cPiKMslZqI)

We need to integrate `pallet_multisig` and `pallet_proxy` in CESS runtime, as shown in the [Substrate codebase](https://github.com/CESSProject/substrate/blob/master/bin/node/runtime/src/lib.rs#L2052-L2053) to use multi-sig feature.

**Is this enough for our use case?**

---
If not, I also found two nice solutions on creating multi-sig account in Substrate chain:

1. [Multix](https://multix.chainsafe.io/)
   - Renowned team behind, Chainsafe
   - Their [treasury proposal voting](https://polkadot.polkassembly.io/motion/357?ref=blog.chainsafe.io) ([proposal text](https://docs.google.com/document/d/1euTuMEFSBwFf4cRVLK8sshI9PgdR5-Qg4ciDN4WJpaA/edit#heading=h.v6is2ta0txr1)).
   - An [early blogpost](https://blog.chainsafe.io/multix-a-simple-interface-to-manage-complex-multisigs-on-polkadot/) with a demo video
   - A [later blogpost](https://blog.chainsafe.io/use-your-multix-multisigs-anywhere/) demoing using WalletConnect
   - [Src repo](https://github.com/ChainSafe/Multix)

2. [PolkaSafe](https://app.polkasafe.xyz/)
   - Engagement in [Polkadot Forum](https://forum.polkadot.network/t/polkasafe-making-multisig-usable-on-polkadot-kusama)
   - [Src repo](https://github.com/polkasafe/polkasafe-sdk)

To use the above two solutions, there is probably some integration work need to be done.

**Comment by ytqaljn** [comment]
It seems that option 1 is enough to achieve our purpose.

**Comment by ytqaljn** [comment]
@jimmychu0807 
I've added them:  https://github.com/CESSProject/cess/pull/262
