### ISSUE TITLE
Adding blockscout (or other EVM blockchain explorer) to monitor the EVM side of CESS

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/cess#261]
We should integrate a EVM blockchain explorer if we really want to push developer to use our Solidity smart contract platform, so it can see the EVM contract transaction details and events emitted. Currently support of seeing EVM txs and events in Polkadot-js apps is minimal.

Ref:
- [Blockscout](https://www.blockscout.com/)

**Comment by ytqaljn** [comment]
I can't open this reference link.
