### ISSUE TITLE
cess tools rotate-keys: output is NULL

### ISSUE THREAD

**Issue by Ovidiv1** [CESSProject/cess#285]
I tried to run an consensus node. All looks fine but when I try to retrieve the keys, the output is NULL. I have bonded 3M Cess with a secondary controller account with 200cess. The node is synchronising with succes also. I don’t know what the problem can be. I attached the config settings also.
![IMG_0051](https://github.com/CESSProject/cess/assets/97460928/6d532f77-5c70-4d47-91e5-7e8086f9833e)

**Comment by Ovidiv1** [comment]
The ws url is  ws://cess-chain:9944. In the photo is another attempt of mine

**Comment by 0xbillw** [comment]
I'm very sorry that this issue has troubled you.
Actually, this problem has been solved.
You need to update your `cess-nodeadm` program.
Thank you!
