### ISSUE TITLE
use hyper_v to intsall ubuntu

### ISSUE THREAD

**Issue by yangxdGIT** [CESSProject/cess#318]
Hello, can the team come up with a tutorial on creating an ubuntu virtual machine with hyper_v on windows and installing docker and cess programs? Because most people have limited technology, and windows is the dominant system. With this tutorial, I believe it will attract more people to participate in the cess project and make it more well-known and bigger

**Comment by jiuquxzy** [comment]
Hello, the CESS team will fully respect and take your suggestions seriously and will take action in the near future.

**Comment by jiuquxzy** [comment]
> Hello, can the team come up with a tutorial on creating an ubuntu virtual machine with hyper_v on windows and installing docker and cess programs? Because most people have limited technology, and windows is the dominant system. With this tutorial, I believe it will attract more people to participate in the cess project and make it more well-known and bigger

Hello, the CESS team will fully respect and take your suggestions seriously and will take action in the near future.
