### ISSUE TITLE
Does CESS support the arm64 platform?

### ISSUE THREAD

**Issue by qingfengzxr** [CESSProject/cess#319]
![微信图片_20240319170805](https://github.com/CESSProject/cess/assets/23336984/663a0ccb-8a7e-4eea-904d-30233726b7a6)

When I run 'cess config set,' I get an error message related to architecture, indicating that a certain running program is not arm64. Can anyone help me with this?

**Comment by yeousunn** [comment]
Hi, @qingfengzxr 
No, ARM architecture is not supported.
