### ISSUE TITLE
SBP: Review all your `unwrap()`

### ISSUE THREAD

**Issue by NachoPal** [CESSProject/cess#35]
Avoid panics at almost any cost and add "proofs" for expect() calls on why they cannot fail. The only reason to panic should be in case a block should not be built when that code path is triggered or when it indicates a bug.

In most cases you should handle the Error.

e.g: A potential place to handle the error: https://github.com/CESSProject/cess/blob/main/c-pallets/file-bank/src/lib.rs#L537

**Comment by swowk** [comment]
Hi, Nacho. Thank you very much for your suggestion, this is very helpful for us. We are making adjustments and will communicate with you when it is fixed.

**Comment by ytqaljn** [comment]
Now we have changed all the places in the code where unwrap() and expect() are used, and we will pay attention to this in future development. PR: (#49)
