### ISSUE TITLE
SBP: Off-chain worker documentation is outdated

### ISSUE THREAD

**Issue by NachoPal** [CESSProject/cess#37]
https://github.com/CESSProject/sbp-code-docs/blob/main/m1/cess-dscm.md

Your off-chain worker is not signing transactions anymore, it is using unsigned transactions instead.

**Comment by ytqaljn** [comment]
Sorry, we have made some changes temporarily. Next, we will change the unsigned transaction to the signed transaction and filter the signers. After completing these works, we will update our documents.
