### ISSUE TITLE
SBP: Off-chain worker configuration

### ISSUE THREAD

**Issue by NachoPal** [CESSProject/cess#39]
The use of off-chain worker for fetching the storage price should improved taking into consideration how they work and when they are executed.

Some context about things to pay attention to when using off-chain workers:
- https://stackoverflow.com/questions/64772897/offchain-workers-signed-transactions/64772985#64772985
- https://stackoverflow.com/questions/59401972/role-of-off-chain-workers
- https://substrate.stackexchange.com/questions/2093/when-does-an-off-chain-worker-get-executed

**Comment by ytqaljn** [comment]
Wow, thank you. I just learned the use of the offline working machine according to ocw-example. I will improve the working mode of the offline working machine according to the documents you provide.

**Comment by ytqaljn** [comment]
Thank you. Now we have changed to accept only the first price from offchain worker. (#59)

**Comment by ytqaljn** [comment]
At present, we have carried out several version iterations, and the content provided above is no longer in use. The link of current implementation is as follow:
https://github.com/CESSProject/cess/blob/v0.5.1/c-pallets/segment-book/src/lib.rs#L755-L924
