### ISSUE TITLE
SBP: Improve cleanliness & readability

### ISSUE THREAD

**Issue by NachoPal** [CESSProject/cess#44]
We recommend you to run
```
cargo +nightly fmt --all -- --check
```

**Comment by swowk** [comment]
CC @ytqaljn

**Comment by ytqaljn** [comment]
I have used cargo FMT for formatting.(#61)

**Comment by heyworld88** [comment]
@NachoPal Thank you for your all suggestion. our developer has made adjustments. You can now check to see if satisfy your requirement. please leave comments free if you have a question.
