### ISSUE TITLE
Error: [err] [DecodeToCessPub]: Invalid addrss.

### ISSUE THREAD

**Issue by jmiranda1996** [CESSProject/cess#82]
Why did I get this message?

<img width="495" alt="Captura de Pantalla 2022-08-12 a la(s) 10 24 32" src="https://user-images.githubusercontent.com/56894248/184387611-2fe6a5bc-de5d-42fe-ac17-855c61c7eb34.png">

**Comment by ytqaljn** [comment]
There is an error in the wallet address filled in the configuration file. Maybe you didn't fill in the address prefixed with 'cX'?
You can refer to the following tutorial:
https://github.com/CESSProject/cess/wiki/Create-a-CESS-Wallet#method-2-create-an-account-in-the-cess-official-blockchain-explorer

**Comment by jmiranda1996** [comment]
Thanks!
